unit EmployeeEntity;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity, Table('Employees')]
  TEmployee = class
  private
    [AutoGenerated, Column('EmployeeID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert])]
    fId: Integer;
    fLastName: string;
    fFirstName: string;
    fTitle: string;
    fTitleOfCourtesy: string;
    fBirthDate: TDateTime;
    fHireDate: TDateTime;
    fAddress: string;
    fCity: string;
    fRegion: string;
    fPostalCode: string;
    fCountry: string;
    fHomePhone: string;
    fExtension: string;
    fReportsTo: string;
  public
    property Id: Integer read fId;

    [Column('LastName', [cpRequired, cpNotNull], 10)]
    property LastName: string read fLastName write fLastName;

    [Column('FirstName', [cpRequired, cpNotNull], 10)]
    property FirstName: string read fFirstName write fFirstName;

    [Column('Title', [], 10)]
    property Title: string read fTitle write fTitle;

    [Column('TitleOfCourtesy', [], 10)]
    property TitleOfCourtesy: string read fTitleOfCourtesy write fTitleOfCourtesy;

    [Column('BirthDate', [], 10)]
    property BirthDate: TDateTime read fBirthDate write fBirthDate;

    [Column('HireDate', [], 10)]
    property HireDate: TDateTime read fHireDate write fHireDate;

    [Column('Address', [], 10)]
    property Address: string read fAddress write fAddress;

    [Column('City', [], 10)]
    property City: string read fCity write fCity;

    [Column('Region', [], 10)]
    property Region: string read fRegion write fRegion;

    [Column('PostalCode', [], 10)]
    property PostalCode: string read fPostalCode write fPostalCode;

    [Column('Country', [], 10)]
    property Country: string read fCountry write fCountry;

    [Column('HomePhone', [], 10)]
    property HomePhone: string read fHomePhone write fHomePhone;

    [Column('Extension', [], 10)]
    property Extension: string read fExtension write fExtension;

    [Column('ReportsTo', [], 10)]
    property ReportsTo: string read fReportsTo write fReportsTo;
  end;

implementation

end.
