unit CategoryEntity;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity, Table('Categories')]
  TCategory = class
  private
    [AutoGenerated, Column('CategoryID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert])]
    fId: Integer;
    fName: string;
    fDescription: string;
  public
    property Id: Integer read fId;

    [Column('CategoryName', [cpRequired, cpNotNull], 15)]
    property Name: string read fName write fName;

    [Column('Description', [], 250)]
    property Description: string read fDescription write fDescription;
  end;

implementation

end.
