unit ProductEntity;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity, Table('Products')]
  TProduct = class
  private
    [AutoGenerated, Column('ProductID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert])]
    fId: Integer;
    fProductName: string;
    FSupplierId: Integer;
    FCategoryId: Integer;
    fQuantityPerUnit: string;
    fUnitPrice: Currency;
    fUnitsInStock: SmallInt;
    fUnitsOnOrder: SmallInt;
    fReorderLevel: SmallInt;
    fDiscontinued: Boolean;
  public
    property Id: Integer read fId;

    [Column('ProductName', [cpRequired, cpNotNull], 40)]
    property ProductName: string read fProductName write fProductName;

    [Column('SupplierID')]
    property SupplierId: Integer read FSupplierId write FSupplierId;

    [Column('CategoryID')]
    property CategoryId: Integer read FCategoryId write FCategoryId;

    [Column('QuantityPerUnit')]
    property QuantityPerUnit: string read fQuantityPerUnit write fQuantityPerUnit;

    [Column('UnitPrice')]
    property UnitPrice: Currency read fUnitPrice write fUnitPrice;

    [Column('UnitsInStock')]
    property UnitsInStock: SmallInt read fUnitsInStock write fUnitsInStock;

    [Column('UnitsOnOrder')]
    property UnitsOnOrder: SmallInt read fUnitsOnOrder write fUnitsOnOrder;

    [Column('ReorderLevel')]
    property ReorderLevel: SmallInt read fReorderLevel write fReorderLevel;

    [Column('Discontinued')]
    property Discontinued: Boolean read fDiscontinued write fDiscontinued;
  end;

implementation

end.
