unit ShipperEntity;

interface

uses
  Spring.Persistence.Mapping.Attributes;

type
  [Entity, Table('Shippers')]
  TShipper = class
  private
    [AutoGenerated, Column('ShipperID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert])]
    fId: Integer;
    fCompanyName: string;
    fPhone: string;
  public
    property Id: Integer read fId;

    [Column('CompanyName', [cpRequired, cpNotNull], 40)]
    property CompanyName: string read fCompanyName write fCompanyName;

    [Column('Phone', [], 24)]
    property Phone: string read fPhone write fPhone;
  end;

implementation

end.
